# development:
#   adapter: async
#   # adapter: redis
#   # adapter: redis://192.168.0.115:3000/1

# test:
#   adapter: test

development:
  adapter: async
  url: ws://192.168.0.115:3000/cable
  # allowed_request_origins: [/^(http|https)\:\/\/(?:\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}|localhost):\d{1,5}$/]
  #   - "http://localhost:3000"
  #   - "http://localhost:3001"
  #   - "http://127.0.0.1:3000"
  #   - "http://192.168.0.115:3000"

test:
  adapter: async
  # allowed_request_origins:
  #   - "http://localhost:3000"
  #   - "http://localhost:3001"
  #   - "http://127.0.0.1:3000"
  #   - "http://192.168.0.115:3000"

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: tru_well_production